# Generated by Django 5.1.1 on 2025-04-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='Изображение к публикации', verbose_name='Изображение'),
        ),
    ]
